apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tpa-test-tas 
  janus-idp.io/tekton: tpa-test-tas
  backstage.io/kubernetes-id: tpa-test-tas
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tpa-test-tas
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  