apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: tpa-test-tas
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tpa-test-tas 
  name: tpa-test-tas
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: tpa-test-tas
    weight: 100 
