apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tpa-test-tas
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tpa-test-tas 
  name: tpa-test-tas
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: tpa-test-tas 
